---
title: "Progress Report"
author: "Emma Livingston"
date: "November 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ma_schools<-read.csv("ma_schools.csv")

pruned_ma_schools <- ma_schools %>%
  select(X10_Enrollment, TOTAL_Enrollment, X..English.Language.Learner, X..Students.With.Disabilities, X..High.Needs, X..Economically.Disadvantaged, X..African.American, X..Asian, X..Hispanic, X..White, X..Native.American, X..Native.Hawaiian..Pacific.Islander, X..Multi.Race..Non.Hispanic, X..Males, X..Females, Total...of.Classes, Average.Class.Size, Number.of.Students, Salary.Totals, Average.Salary, FTE.Count, In.District.Expenditures, Total.In.district.FTEs, Average.In.District.Expenditures.per.Pupil, Total.Expenditures, Total.Pupil.FTEs, Average.Expenditures.per.Pupil, X..Graduated, X..Still.in.School, X..Non.Grad.Completers, X..GED, X..Dropped.Out, X..Permanently.Excluded, X..Attending.College,  X..MCAS_10thGrade_English_A, X..MCAS_10thGrade_English_NI, X..MCAS_10thGrade_English_P, X..MCAS_10thGrade_English_P.A, X..MCAS_10thGrade_English_W.F, X..MCAS_10thGrade_Math_A, X..MCAS_10thGrade_Math_NI, X..MCAS_10thGrade_Math_P, X..MCAS_10thGrade_Math_P.A, X..MCAS_10thGrade_Math_W.F)

pruned_ma_schools$proficiency_index = (pruned_ma_schools$X..MCAS_10thGrade_English_P.A + pruned_ma_schools$X..MCAS_10thGrade_Math_P.A) / 2

str(pruned_ma_schools, give.attr = FALSE)
pruned_ma_schools<- na.omit(pruned_ma_schools)

pruned_ma_schools <- pruned_ma_schools %>%
  filter(X10_Enrollment != 0)
## get rid of schools that don't offer 10th grade
```


```{r}
null_model <- lm(proficiency_index ~ 1, data = pruned_ma_schools)

full_model <- lm(proficiency_index ~ X..English.Language.Learner + X..Students.With.Disabilities + X..Economically.Disadvantaged + X..White + X..Females + Average.Class.Size + Average.Salary + Average.Expenditures.per.Pupil, data = pruned_ma_schools)

fullMSE <- (summary(full_model)$sigma)^2

stepwise_full <- step(null_model, scope = list(upper = full_model), scale = fullMSE, direction = "both")
```

 